version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynet

  xdl.internship.scheduler.servicehost:
    build: .
    networks:
      - mynet
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure

networks:
  mynet:
    external:
      name: mynet
